# Generated by Django 4.2.8 on 2024-01-04 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='Updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
